### ISSUE TITLE
Issues with logos and a local BBC station

### ISSUE THREAD

**Issue by thearchitectuk** [dp247/Freeview-EPG#35]
I'm using Sparkle TV, a particularly excellent Live TV app for Android TV. With it, I'm using an HDHomeRun Duo as the source.

When I input the EPG.xml link, I'd say it's about 75% correct. I've noticed 3 issues in particular.

1. Some channels (ITV HD, Channel 4 HD, 5 HD, and others), show the guide data and the program thumbnail fine. However there's no channel logo.
2. BBC HD South West shows nothing at all.
3. BBC News and BBC parliament both say ... Programmes no longer available

Thanks

**Comment by dp247** [comment]
I'll take a look at them sometime - things change so are maybe just broken. Do you have any logs for your the app? They'd be helpful in debugging the first issue, because the logos definitely are present.

**Comment by thearchitectuk** [comment]
Thanks for this. Sadly there are no logging features in Sparkle TV. I think I can manually map images for the missing ones, but the main problem I suppose is the local BBC HD South West channel.

**Comment by dp247** [comment]
Okay cool, I'll check it out in the next couple of days 😊

**Comment by dp247** [comment]
Hello again,
I did some digging - I've updated the source IDs for BBC News/BBC Parliament because they were changed in the BBC SD shutdown. That's the good news - the bad news is I cannot reproduce your first two issues - BBC SW seems okay in the latest release of the guide (20 mins ago):
![image](https://github.com/dp247/Freeview-EPG/assets/9065463/6cee87a5-0ff0-45ed-8948-51ae5469009b)

I did see [this ](https://www.reddit.com/r/SparklePlayer/comments/196lh8o/epg/)on Reddit though, which might explain the logo issue (again, it's something I can't reproduce in my setup, and I don't want to pay £18 for the app 😅) - have you tried any other apps?

**Comment by thearchitectuk** [comment]
I think you might be right regarding the missing logos! Not sure what's going on with the BBC One SW channel though :-/ 

I mean if I'm struggling, I'm happy to send you some $$ for the app! ;-)

**Comment by dp247** [comment]
Still can't repro, feel free to reopen if its still an issue
