### ISSUE TITLE
How to import channels to usb so can import straight to tv 

### ISSUE THREAD

**Issue by Lovetech550** [dp247/Freeview-EPG#42]
Hi im new to here but i was searching download uk data channels and you popped i was looking to download channels to usb to import tv is this what i can do and how would i do that or would you kindly be able to send me the channels via wetransfer so all i would have to do is import to usb then tv i would also be happy to contribute to your project i hope to get a response and thank you in advance

**Comment by dp247** [comment]
Not sure if it's possible to import the data directly to a TV via USB. The file that has all the EPG data is available [here](https://github.com/dp247/Freeview-EPG/blob/master/epg.xml) though. What is the model of the TV?

**Comment by Lovetech550** [comment]
The model is a samsung tv you can import and export channels from a tv but i am not sure tv format needs to be 

https://m.youtube.com/watch?v=cdZ0IDwxBU0&pp=ygUbRXhwb3J0IHR2IGNoYW5uZWxzIHZpYSB1c2Ig

**Comment by Lovetech550** [comment]
How for example would i upload this to a usb sorry for sounding really silly im not a tech savvy as you

**Comment by dp247** [comment]
Don't apologize - thanks for opening an issue! 

Judging by the service manual for those TVs, it looks like the channel import feature is for when you're resetting the TV and don't want to wait for automatic tuning to complete - so you can export the channels to a USB, reset the TV and then import them from the USB.

Unfortunately, that means that you can't use the data provided by this project since this project doesn't supply actual channels you can watch (only the data of what's on), and wouldn't be in the required format.

**Comment by Lovetech550** [comment]
Ok say for example you export channels from your tv right now its just the script of the channels the tv is looking for i suppose we can give it a try if you could tell me how to download channels

**Comment by dp247** [comment]
The data is stored in the EPG file here:
https://github.com/dp247/Freeview-EPG/blob/master/epg.xml

The download button is here, and will download the latest EPG as an XML file:
![image](https://github.com/dp247/Freeview-EPG/assets/9065463/b3c2b073-9b62-40f5-ac5b-93b5cb77df6c)

**Comment by Lovetech550** [comment]
Ok thanks very much will try will message let you know outcome aswell brb
